source 'https://rubygems.org'

gem 'sinatra', '~> 3.0'
gem 'sinatra-cors', '~> 1.2'
gem 'json', '~> 2.6'
gem 'dotenv', '~> 2.8'
gem 'puma', '~> 6.3'  # Servidor web para produção

group :development do
  gem 'rerun', '~> 0.14'  # Para reiniciar automaticamente o servidor durante o desenvolvimento
end